// Generated by scripts/card-art.mjs — do not edit by hand.
import type { CardKey, CharKey, EventKey } from "./cards";

/** card-<card type> · char-<character> · event-<event card> · back (the playing-card back). */
export type BangArt = `card-${CardKey}` | `char-${CharKey}` | `event-${EventKey}` | "back";

/**
 * Art files in public/games/bang/cards/<name>.webp.
 * Everything else keeps the drawn face (colour + emoji), so art can be added a few cards at a time.
 */
export const BANG_ART: readonly BangArt[] = [];

/** Changes whenever the images change, so browsers don't keep old ones. */
export const BANG_ART_VERSION = "0";
