#!/usr/bin/env node
/**
 * Mèo Nổ card art: turn source images into the game's card images.
 *
 *   npm run art:meono               # reads art/meono/*
 *   npm run art:meono -- path/to/dir
 *
 * Name each source file after the card type — `defuse.png`, `nope.jpg`, `exploding.webp`… — plus
 * `back.png` for the card back (the list of types is in src/lib/meono/cards.ts, and
 * docs/MEONO_ART_PROMPTS.md has one prompt per card). Each image is cropped to 5:7, resized to
 * 400×560 and saved as public/games/meono/cards/<type>.webp, then src/lib/meono/art.ts is
 * rewritten so the game knows which cards have art. Cards without art keep the drawn face.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, extname, join, resolve } from "node:path";
import sharp from "sharp";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = resolve(process.argv[2] ?? join(ROOT, "art/meono"));
const OUT = join(ROOT, "public/games/meono/cards");
const MANIFEST = join(ROOT, "src/lib/meono/art.ts");
const W = 400;
const H = 560;

// Card types, read from the CARDS table so this never drifts from the game.
const cardsTs = readFileSync(join(ROOT, "src/lib/meono/cards.ts"), "utf8");
const table = cardsTs.slice(cardsTs.indexOf("export const CARDS"));
const TYPES = new Set([...table.matchAll(/^ {2}([a-z0-9]+): \{/gm)].map((m) => m[1]));
TYPES.add("back");

if (!existsSync(SRC)) {
  console.error(`Không thấy thư mục ảnh nguồn: ${SRC}`);
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });
const done = [];
const unknown = [];
for (const file of readdirSync(SRC).sort()) {
  const ext = extname(file).toLowerCase();
  if (![".png", ".jpg", ".jpeg", ".webp", ".avif"].includes(ext)) continue;
  const type = basename(file, extname(file)).toLowerCase();
  if (!TYPES.has(type)) {
    unknown.push(file);
    continue;
  }
  await sharp(join(SRC, file))
    .rotate()
    .resize(W, H, { fit: "cover", position: sharp.strategy.attention })
    .webp({ quality: 82, effort: 6 })
    .toFile(join(OUT, `${type}.webp`));
  done.push(type);
}

// The manifest lists every image in the output folder, not just this run's.
const have = readdirSync(OUT)
  .filter((f) => f.endsWith(".webp") && TYPES.has(basename(f, ".webp")))
  .map((f) => basename(f, ".webp"))
  .sort();
const hash = createHash("sha1");
for (const t of have) hash.update(t).update(readFileSync(join(OUT, `${t}.webp`)));
const version = have.length ? hash.digest("hex").slice(0, 8) : "0";

writeFileSync(
  MANIFEST,
  `// Generated by scripts/meono-art.mjs — do not edit by hand.
import type { CardType } from "./cards";

/**
 * Card types that have artwork in public/games/meono/cards/<type>.webp ("back" = the card back).
 * Everything else keeps the drawn face (colour + emoji), so art can be added a few cards at a time.
 */
export const MEO_ART: readonly (CardType | "back")[] = [${have.map((t) => JSON.stringify(t)).join(", ")}];

/** Changes whenever the images change, so browsers don't keep old ones. */
export const MEO_ART_VERSION = ${JSON.stringify(version)};
`,
);

const missing = [...TYPES].filter((t) => !have.includes(t)).sort();
console.log(`Đã chuyển ${done.length} ảnh${done.length ? `: ${done.join(", ")}` : ""}.`);
if (unknown.length) console.log(`Bỏ qua (tên không khớp loại lá nào): ${unknown.join(", ")}`);
console.log(`Có ảnh: ${have.length}/${TYPES.size}.${missing.length ? ` Còn thiếu: ${missing.join(", ")}` : ""}`);
