// Generated by scripts/meono-art.mjs — do not edit by hand.
import type { CardType } from "./cards";

/**
 * Card types that have artwork in public/games/meono/cards/<type>.webp ("back" = the card back).
 * Everything else keeps the drawn face (colour + emoji), so art can be added a few cards at a time.
 */
export const MEO_ART: readonly (CardType | "back")[] = [];

/** Changes whenever the images change, so browsers don't keep old ones. */
export const MEO_ART_VERSION = "0";
