// Generated by scripts/card-art.mjs — do not edit by hand.
import type { CardType } from "./cards";

/**
 * Card types that have artwork in public/games/meono/cards/<type>.webp ("back" = the card back).
 * Everything else keeps the drawn face (colour + emoji), so art can be added a few cards at a time.
 */
export const MEO_ART: readonly (CardType | "back")[] = ["alter", "alternow", "annoy", "attack", "back", "barking", "beard", "bottom", "bury", "catomic", "clairvoyance", "clone", "corn", "curse", "deadattack", "defuse", "dig", "exploding", "favor", "feed", "feral", "future", "future5", "garbage", "grave", "ilt", "imploding", "mark", "melon", "nope", "personal", "potato", "potluck", "rainbow", "reverse", "rollcall", "share", "shuffle", "skip", "slap", "steal", "streaking", "superskip", "swap", "taco", "targeted", "zombie"];

/** Changes whenever the images change, so browsers don't keep old ones. */
export const MEO_ART_VERSION = "48d93267";
